
setup:
	apt-get install tmux
	pip3 install netifaces
	pip3 install prompt_toolkit
	pip3 install colored
	pip3 install libtmux
	pip3 install validators
	pip3 install multipart
	
	chmod +x plugins/metasploit/msf/msfpc.sh

keys:
	openssl req -nodes -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
